source 'https://cdn.cocoapods.org/'

platform :ios, '14.0'

target 'SwiftUnity' do
  pod 'Firebase/Analytics', '10.13.0'
  pod 'Firebase/Core', '10.13.0'
  pod 'Firebase/Crashlytics', '10.13.0'
  pod 'Firebase/Firestore', '10.13.0'
  pod 'Firebase/Functions', '10.13.0'
end
use_frameworks! :linkage => :static
